### ISSUE TITLE
Make plugin related sounds customizable  

### ISSUE THREAD

**Issue by WolfNT90** [WolfNT90/berries-jar#3]
This is a feature I've already thought about working on.
Possible way for implementing would be to **A)**
```yml
customSounds:
   playerJoinMessage: UI_BUTTON_CLICK, .7, 3
```
Implement a special category in the `config.yml` file like that.

Or **B)**
```yml
sounds:
   chatMessages: UI_BUTTON_CLICK, .7, 3
   playerJoinMessage: none
```
Turn the existing entries from `boolean`s to outright sound entries, with `none` being the safe-word for there being no sound.
